# If Debug is set to "true" every event will get logged
debug: false

# Enable if AFK status to be checked, and AFK time NOT counted
afkPlayerCheck: true

# Enable if data should be saved to disk on scheduled event. Otherwise it will happen on server shutdown only
autoSave: true

# If auto save is enabled above, how frequently (in minutes) should this be done.
autoSavePeriod: 5

# Maximum length of 'top player' lists
topListMax: 10

# MySQL
mysql:
  host: 127.0.0.1
  port: 3306
  user:
  table:
  password:
  database:

# Strings
PluginPrefix: "OnTime"
Name: "Name:"
Playtime: "Playtime:"
Joined: "Joined at:"
Player: "Player"
Days: "Days"
Hours: "Hours"
Minutes: "Minutes"
Seconds: "seconds"
Second: "second"
Time: "Time"
Statistic: "Playtime Statistics"
HelpPage: "Help Page"

# Informations:
ConnectionToSQLClosed: "The connection to the database has been disconnected."
ClearMessage: "The stored data from player %s has been successfully deleted."
AddTimeMessage: "%d %s were added to the player %s."
RemoveTimeMessage: "%d %s were taken from the player %s."
ConsoleError: "Hey you! You can't execute that command from the console."

# Error-Messages:
NotAnIntegerError: "Please enter a number that is greater than 0."
CommandIsMissingArgsError: "This command is not complete."
PlayerNotFoundError: "The specified player could not be found."
ExecuteError: "An error occurred while executing the command."
AmountHigherThanPlaytimeError: "The specified time is greater than the playing time of this player. A player cannot have negative playing time."
NoConnectionToSQLError: "Could not connect to the database."
NoPermissionError: "You do not have the permission to do this."

# Debug-Messages:
PlayerJoin: "Tracking playtime from %s ..."
PlayerQuit: "Player disconnected. Saving playtime from %s."
Clear: "The player %s was removed from the database by %s."
Remove: "The player %s was taken %d %s from %s."
AddTime: "The player %s was added %d %s from %s."
PlayerAFK: "Player %s is afk, stop tracking."
PlayerNotAFK: "Player %s is back, continuing tracking..."
ConfigReloaded: "Config was reloaded successfully."

# Help-Messages:
CheckCommandHelpMessage: "Shows you your playing time."
CheckOthersCommandHelpMessage: "Check the online time of the player."
TopCommandHelpMessage: "Check out the online time of the top 10 players."
AddTimeCommandHelpMessage: "Adds the specified time to the player."
RemoveTimeCommandHelpMessage: "Removes the specified time from the player."
ClearCommandHelpMessage: "Removes the stored data from the specified player."
ReloadHelpMessage: "Reloads the config."

# Warnings:
NoUndoWarning: "Attention: This cannot be undone!"