# If Debug is set to "true" every event will get logged
debug: true

# Enable if AFK status to be checked, and AFK time NOT counted
afkPlayerCheck: true

# Enable if data should be saved to disk on scheduled event. Otherwise it will happen on server shutdown only
autoSave: true

# If auto save is enabled above, how frequently (in minutes) should this be done.
autoSavePeriod: 5

#SleepTimer is the time how long a new player has to be on the server to create a new file for him (0 = off, in minutes)
SleepTimer: 10

# maximum length of 'top player' lists
topListMax: 10

#Plugin Prefix
PluginPrefix: "§f[§cOnTime§f] "

PlayerName: "§6Name:§r§l"
PlayTime: "§6Playtime:§r§l"
PlayerJoinDate: "§6Joined at:§r§l"

DaysValue: "Tage"
HoursValue: "Stunden"
MinutesValue: "Minuten"
PlayerValue: "Spieler"

#Error Messages:
NotAnIntegerError: "§4Bitte gebe eine Zahl ein die größer als 0 ist."
PlayerNotFoundError: "§4Der angegebene Spieler konnte nicht gefunden werden."
CommandIsMissingArgsError: "§4Dieser Befehl ist nicht vollständig."
AmountHigherThanPlayTimeError: "§4Die angegebene Zeit ist größer als die Spielzeit von diesem Spieler. Ein Spieler kann keine Negative Spiezeit besitzen."
OntimeAddUsage: "Usage: /ontime add [Player] [Zeit in Sekunden]"
OntimeRemoveUsage: "Usage: /ontime Remove [Player] [Zeit in Sekunden]"

# MySQL
mysql:
  host: localhost
  port: 3306
  user: root
  password:
  database:
